//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DruckLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class Druckauftrag
    {
        public int Id { get; set; }
        public string BauteilURL { get; set; }
        public int ersteller { get; set; }
        public Nullable<int> bearbeiter { get; set; }
        public Nullable<System.DateTime> gestartet { get; set; }
        public string Material { get; set; }
    
        public virtual Person Erstellt { get; set; }
        public virtual Person Bearbeitet { get; set; }
    }
}
